.circleci/config.yml
Dockerfile
pinot-servicemanager/Dockerfile

we are still publishing release on commit!

ci: migrate release to tag triggers

---

README.md

This PR
- Adds one liner to answer question `what is pinot?`
- Adds answer to question `how do we use pinot?`
- Adds architecture diagram showing Pinot's place in Hypertrace architecture.

adds what is pinot and how do we use it and architecture diagram in README

---

pinot-servicemanager/Dockerfile
pinot-servicemanager/docker-bin/docker-healthcheck
pinot-servicemanager/docker-bin/install-schema
pinot-servicemanager/docker-bin/start-servicemanager

you can try with this but anyway https://github.com/hypertrace/hypertrace/pull/45
after running `./gradlew dockerBuildImages`
TODO: port to wget

Automatically installs schema on start

---

BUILD.md
README.md

this PR
- adds testing section which includes how we can use locally built image using docker-compose as well as helm setup. 
- updates architecture diagram and sections
- moves build details to BUILD.md

Adds testing section and updates architecture diagram in README

---

pinot-servicemanager/docker-bin/docker-healthcheck
pinot-servicemanager/docker-bin/start-servicemanager
pinot-servicemanager/install.sh

This reduces the changes in #48 to only those required for the java addTable command

Cleans up servicemanager scripts

---

pinot-servicemanager/schemas/backendEntityView-schemaFile.json
pinot-servicemanager/schemas/rawServiceView-schemaFile.json
pinot-servicemanager/schemas/rawTraceView-schemaFile.json
pinot-servicemanager/schemas/serviceCallView-schemaFile.json
pinot-servicemanager/schemas/spanEventView-schemaFile.json

hypertrace/hypertrace#142
Add schema changes for spaces support
Manually spun up HT with local pinot image

chore: schema changes to add spaces support

---

helm/templates/controller/configmap.yaml
helm/values.yaml

Please include a summary of the change, motivation and context.
Please describe the tests that you ran to verify your changes. Please summarize what did you test and what needs to be tested e.g. deployed and tested helm chart locally. 
Make sure that you have documented corresponding changes in this repository or [hypertrace docs repo](https://github.com/hypertrace/hypertrace-docs-website) if required.

Templatize deleted segments retention period

---

helm/templates/broker/jmx-configmap.yaml
helm/templates/controller/jmx-configmap.yaml
helm/templates/server/jmx-configmap.yaml

Add JVM and GC metrics to JMX filter rules for better monitoring.

Add jvm metrics to jmx filter rules

---

README.md

This PR, 
- Updated architecture diagram for query layer architecture in README
NA
- https://docs.hypertrace.org/arch/

docs: updated architecture diagram in README

---

pinot-servicemanager/schemas/spanEventView-schemaFile.json

Related to https://github.com/hypertrace/hypertrace-ingester/pull/138

Pinot: Add api_exit_calls field 

---

.github/workflows/pr-build.yml
Dockerfile
helm/Chart.yaml
pinot-avro-serde/build.gradle.kts
pinot-servicemanager/Dockerfile
pinot-udf/build.gradle.kts

Pinot 0.7.1 upgrade. Enables us to use minion framework and try our several other important new features and bug fixes.
Please describe the tests that you ran to verify your changes. Please summarize what did you test and what needs to be tested e.g. deployed and tested helm chart locally. 
Make sure that you have documented corresponding changes in this repository or [hypertrace docs repo](https://github.com/hypertrace/hypertrace-docs-website) if required.

pinot upgrade

---

pinot-servicemanager/schemas/logEventView-schemaFile.json

Add summary col
hypertrace/hypertrace#224

feat: summary col

---

helm/templates/controller/configmap.yaml
helm/values.yaml

Enable task scheduler configuration in controller.
Deployed and tested helm chart locally.

Enable task scheduler configuration in controller

---

helm/templates/minion/configmap.yaml

Fixes the hostname for minion component
Config change tested locally.

minion hostname config fix

---

Dockerfile

https://github.com/hypertrace/incubator-pinot/releases/tag/hypertrace-0.7.1-6

upgrade pinot to release 0.7.1-6

---

Dockerfile
helm/templates/controller/configmap.yaml
helm/templates/server/configmap.yaml
helm/values.yaml

Upgrade to hypertrace-0.7.1-7

---

pinot-servicemanager/schemas/spanEventView-schemaFile.json

Ref issue : hypertrace/hypertrace-ui#1157

Adding span count attribute

---

Dockerfile

https://github.com/hypertrace/incubator-pinot/releases/tag/hypertrace-0.7.1-10

upgrade log4j version to 2.17.0

---

helm/templates/broker/poddisruptionbudget.yaml
helm/templates/controller/poddisruptionbudget.yaml
helm/templates/minion/poddisruptionbudget.yaml
helm/templates/server/configmap.yaml
helm/templates/server/poddisruptionbudget.yaml
helm/templates/server/service-headless.yaml
helm/templates/server/service.yaml
helm/templates/server/servicemonitor.yaml
helm/templates/server/statefulset.yml
helm/templates/server/tags-job.yaml
helm/templates/servicemanager/poddisruptionbudget.yaml

`mergeOverwrite` overwrites the first source values resulting in values from preceding tiers to carry forward to later tiers.

fix merge overwrite issue in server templates

---

Dockerfile

upgrade pinot version

---

helm/templates/broker/service.yaml
helm/templates/broker/servicemonitor.yaml
helm/templates/broker/statefulset.yml
helm/templates/controller/service.yaml
helm/templates/controller/servicemonitor.yaml
helm/templates/controller/statefulset.yaml
helm/templates/minion/service.yaml
helm/templates/minion/servicemonitor.yaml
helm/templates/minion/statefulset.yml
helm/templates/server/service.yaml
helm/templates/server/servicemonitor.yaml
helm/templates/server/statefulset.yml
helm/values.yaml

1. update prometheus-jmx-exporter container docker image
2. Rename port for istio explicit protocol selection

update prometheus-jmx-exporter container docker image

---

Dockerfile
pinot-servicemanager/Dockerfile

Patch version upgrade.
Manual testing. 
NA.

pinot patch version upgrade
