- helm/templates/_helpers.tpl
- helm/templates/broker/statefulset.yml
- helm/templates/controller/statefulset.yaml
- helm/templates/server/statefulset.yml
- helm/values.yaml
This will allow us to override both repository and tag of docker image to deploy.
> Allow overriding pinot image tag in helm chart

- .circleci/config.yml
`release-charts step` in circleci workflow failed while releasing new version of pinot:
```
Either git or ssh (required by git to clone through SSH) is not installed in the image. Falling back to CircleCI's native git client but the behavior may be different from official git. If this is an issue, please use an image that has official git and ssh installed.
Enumerating objects: 9, done.
Counting objects: 100% (9/9), done.
Compressing objects: 100% (9/9), done.
Total 189 (delta 0), reused 9 (delta 0), pack-reused 180
reference not found
```
> Remove trigger tag after publishing the helm chart

- .circleci/config.yml
fixes circleci issue:
```
#!/bin/sh -eo pipefail
git tag -am "Released by $CIRCLE_USERNAME" $(git describe --abbrev=0 --tags | sed 's/^release-//')
*** Please tell me who you are.
Run
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
to set your account's default identity.
Omit --global to set the identity only in this repository.
fatal: unable to auto-detect email address (got 'root@88789f782dd3.(none)')
Exited with code exit status 128
CircleCI received exit code 128
```
> set git config before adding a release tag

- .circleci/config.yml
updated image version has `openssh-client` package installed. This will fix the following error in circleci:
```
#!/bin/sh -eo pipefail
git push origin refs/tags/$(git describe --abbrev=0) :refs/tags/release-$(git describe --abbrev=0)
error: cannot run ssh: No such file or directory
fatal: unable to fork
Exited with code exit status 128
CircleCI received exit code 128
```
> update helm-gcs-packager image version in circleci config

- pinot-servicemanager/install
When https://github.com/apache/incubator-pinot/issues/5974 is addressed, we can back out this
> Removes excessive logging from Helix

- .github/workflows/docker-tests.yml
- .github/workflows/servicemanager/docker-compose.yml
This uses GitHub Actions to test the pinot-servicemanager image so that
maintainers have a harder time breaking it by accident. For example, a
change that crashes the image will fail this test.
> Uses GitHub Actions to test pinot-servicemanager on PR and merge

- .circleci/config.yml
- pinot-servicemanager/Dockerfile
If a single invocation of health check exceeds the timeout, the
container is marked unhealthy. This doubles the value as recently
failures have happened due to timeout during bootstrap of
hypertrace/hypertrace/docker
> Doubles health check timeout

- pinot-servicemanager/Dockerfile
- pinot-servicemanager/docker-bin/install-schema
I'm not entirely sure why it is so slow, but the net startup time of
Pinot is very close to one minute again (after schema install).
This change helps us know exactly how slow things are, so that
workarounds can act accordingly.
> Shows in console output how slow startup is with ServiceManager

- .circleci/config.yml
- .github/workflows/docker-tests.yml
- pinot-servicemanager/Dockerfile
- pinot-servicemanager/docker-bin/install-schema
- pinot-servicemanager/docker-bin/start-servicemanager
- pinot-servicemanager/install.sh
This makes logging more succinct and clear, especially when grepping for 'since'
```bash
pinot                   | 08:46:22,986 INFO  [main] command.StartServiceManagerCommand (StartServiceManagerCommand.java:285) - Starting a Pinot [SERVICE_MANAGER] at 0.007s since launch
pinot                   | 08:46:27,220 INFO  [main] command.StartServiceManagerCommand (StartServiceManagerCommand.java:287) - Started Pinot [SERVICE_MANAGER] instance [ServiceManager_20da8f16c3fb_7098] at 4.242s since launch
pinot                   | 08:46:27,246 INFO  [main] command.StartServiceManagerCommand (StartServiceManagerCommand.java:285) - Starting a Pinot [CONTROLLER] at 4.268s since launch
pinot                   | 08:46:32,430 INFO  [main] command.StartServiceManagerCommand …
```
> Moves to Jitpack for service manager and cleans logs

- .circleci/config.yml
- Dockerfile
- build.gradle.kts
- helm/Chart.yaml
- pinot-servicemanager/Dockerfile
- pinot-servicemanager/build.gradle.kts
- pinot-servicemanager/docker-bin/start-servicemanager
- pinot-udf/build.gradle.kts
- pinot-udf/src/main/java/org/apache/pinot/scalar/function/hypertrace/HypertraceScalarFunctions.java
- settings.gradle.kts
Still a WIP, but since @buchi-busireddy was asking about this today - here's where I'm at right now. I'll need to update the other pinot image with the plugins at some point too, but the single container flavor is easier to test
> feat: add udfs to pinot image

- helm/templates/broker/log-configmap.yaml
- helm/templates/broker/statefulset.yml
- helm/templates/controller/log-configmap.yaml
- helm/templates/controller/statefulset.yaml
- helm/templates/server/log-configmap.yaml
- helm/templates/server/statefulset.yml
- helm/values.yaml
By default, only `warn` logs are printed on the console. Overriding log4j2.xml file for pinot broker, controller and server.
> chore: print all logs on the console

- helm/templates/controller/statefulset.yaml
- helm/templates/server/statefulset.yml
pinot-servers takes a lot of time for loading segments during startup. Due to which, http based liveness probes fail and restart the pods.
> use tcp liveness probe for controller and server

- helm/templates/server/service-headless.yaml
- helm/templates/server/statefulset.yml
- helm/values.yaml
During pinot-server startup, the segments are marked online but brokers are not able to access them as the DNS record for the pod will not be created till the pod is in ready state. Hence, the queries fails during the startup period.
Now, the pod DNS record will be created even if the pod is not ready.
> create DNS record for pinot servers before the pods are ready

- pinot-servicemanager/docker-bin/start-servicemanager
- pinot-servicemanager/install.sh
This will help in an issue - https://github.com/hypertrace/pinot/issues/26 (see for more details)
This will help in overriding log level by
```
environment:
- LOG_LEVEL=error
```
> exposing env property for changing log level for servicemanager

- .github/workflows/docker-tests.yml
Earlier we were running CI on every single change including changes in README file which is not necessary at all. 
As @adriancole suggested GitHub actions supports path filters which we can use to avoid running CI on changes in markdown or text files. 
This PR adds path filters in GitHub action based CI running in this repo. 
Tested with changes in GH action. 
References for this PR:
- https://github.community/t/using-on-push-tags-ignore-and-paths-ignore-together/16931
- https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
>  Avoids running CI build on markdown or text file changes

- pinot-udf/build.gradle.kts
- pinot-udf/src/main/java/org/apache/pinot/scalar/function/hypertrace/HypertraceScalarFunctions.java
- pinot-udf/src/test/java/org/apache/pinot/scalar/function/hypertrace/HypertraceScalarFunctionsTest.java
Adding scalar function(udf) for conditional and string equals. A follow up to https://github.com/hypertrace/attribute-service/pull/31
Added unit tests for the existing and new UDFs
- [ ✅ ] My changes generate no new warnings
- [ ✅ ] I have added tests that prove my fix is effective or that my feature works
- [✅  ] Any dependent changes have been merged and published in downstream modules
> feat: add udf for conditional and stringequals

- .github/workflows/docker-tests.yml
While trying POC on GitHub action we realised that docker 19.03 and Java 11 are part of runner that comes with Ubuntu-20.04 already has those requirements satisfied. (ref: https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md)
NA
- https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md
> optimised docker CI test in GH action

- pinot-servicemanager/schemas/backendEntityView-schemaFile.json
Adding backend_operation column in pinot_servicemanager column as we are working on adding `Operation` column in Backend Trace (call) view. 
NA
Make sure that you have documented corresponding changes in this repository or [hypertrace docs repo](https://github.com/hypertrace/hypertrace-docs-website) if required.
> feat: adding backend_operation column in pinot_servicemanager schema

- pinot-servicemanager/schemas/backendEntityView-schemaFile.json
Adding backend_destination column in pinot_servicemanager schema as we are working on adding Destination column in Backend Trace (call) view.
NA
> chore: adds backend_destination column in servicemanager schema

- pinot-servicemanager/schemas/spanEventView-schemaFile.json
- Adds api_trace_error_count column as per changes here: https://github.com/hypertrace/hypertrace-ingester/pull/172
NA
> chore: adds api_trace_error_count column

- pinot-udf/build.gradle.kts
- pinot-udf/src/main/java/org/apache/pinot/scalar/function/hypertrace/HypertraceScalarFunctions.java
- pinot-udf/src/test/java/org/apache/pinot/scalar/function/hypertrace/HypertraceScalarFunctionsTest.java
The behavior of pinot's concat was inconsistent with our expected attribute projection behavior implemented in memory. This change adds both variants of our in memory implementation.
Unit tests
> refactor: update concat support

- helm/templates/minion/configmap.yaml
- helm/templates/minion/statefulset.yml
Minions should be able to download and upload segments from/to gcs/s3 deepstores.
Deployed and tested helm chart locally. 
NA
> Minion config fix to work with deepstores

- Dockerfile
This will allow us to build docker image from forked repo: https://github.com/hypertrace/incubator-pinot.
> Build docker image using jitpack build

- helm/templates/minion/configmap.yaml
- helm/templates/minion/statefulset.yml
- helm/values.yaml
Pinot minion were using `/tmp` folder for RealtimeToOfflineSegmentsTask tasks.
> Mount a separate volume on minion pods

- Dockerfile
Fixes: https://github.com/apache/pinot/issues/8075
```
2022/03/15 12:19:03.217 ERROR [LLCSegmentCompletionHandlers] [grizzly-http-server-21] Caught exception while uploading segment: domainEventView__0__0__20220315T0540Z from instance: Server_pinot-server-2.pinot-server.traceable.svc.cluster.local_8098
com.google.cloud.storage.StorageException: 400 Bad Request
{
"error": {
"code": 400,
"message": "Bad Cloud KMS crypto key: projects/dataservices-0001/locations/europe-west3/keyRings/saas-eu/cryptoKeys/saas-eu-gcs-crypto-key/cryptoKeyVersions/1",
"errors": [
{
"message": "Bad Cloud KMS crypto key: projects/dataservices-0001/locations/europe-west3/keyRings/saas-eu/cryptoKeys/saas-eu-gcs-crypto-key/cryptoKeyVersions/1",
"domain": "global",
"reason": "invalid"
}
]
}
}
```
Cherry picked from …
> Updating gcloud libraries to fix underlying issue with api's with CMEK

- pinot-servicemanager/schemas/backendEntityView-tableConfigFile.json
- pinot-servicemanager/schemas/logEventView-tableConfigFile.json
- pinot-servicemanager/schemas/rawServiceView-tableConfigFile.json
- pinot-servicemanager/schemas/rawTraceView-tableConfigFile.json
- pinot-servicemanager/schemas/serviceCallView-tableConfigFile.json
- pinot-servicemanager/schemas/spanEventView-tableConfigFile.json
With the latest pinot image, if the default group id is null, it doesn't report offset. So, adding group.id for table config schema.
> fix: adds group.id as part of stream config

- Dockerfile
- helm/templates/controller/statefulset.yaml
- helm/values.yaml
1. fix vulnerabilities in docker image
2. add capability to mount existing claim in pinot controller pods
3. update prometheus-jmx-exporter image version
> fix vulnerabilities in docker image

- helm/templates/server/tags-job.yaml
- helm/values.yaml
This is required for non-istio environments.
> add boolean flag to wait for side car

- helm/templates/broker/service-external.yaml
- helm/templates/broker/service-headless.yaml
- helm/templates/broker/service.yaml
- helm/templates/broker/statefulset.yml
- helm/templates/controller/service-headless.yaml
- helm/templates/controller/service.yaml
- helm/templates/controller/statefulset.yaml
- helm/templates/minion/service-headless.yaml
- helm/templates/minion/service.yaml
- helm/templates/minion/statefulset.yml
- helm/templates/server/configmap.yaml
- helm/templates/server/service-headless.yaml
- helm/templates/server/service.yaml
- helm/templates/server/statefulset.yml
- helm/values.yaml
In order to support large data scanning, Pinot [0.6.0, 0.10.0] introduces a gRPC server for on-demand data scanning with a reasonably smaller memory footprint.
You can enable it by adding the below configs to the Pinot server config file:
```
pinot.server.grpc.enable=true
pinot.server.grpc.port=8090
```
> add grpc and admin ports to pinot server service
